# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Caw < Formula
  desc "Monitor your AI coding assistants"
  homepage "https://github.com/pablovilas/caw"
  version "0.0.5"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/pablovilas/caw/releases/download/v0.0.5/caw_0.0.5_darwin_arm64.tar.gz"
    sha256 "2a06162bc87464c597414c4783613b33b3cae1fad4fac7adadff13e7fec116f2"

    define_method(:install) do
      bin.install "caw"
    end
  end

  test do
    system "#{bin}/caw", "--help"
  end
end
