# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Caw < Formula
  desc "Monitor your AI coding assistants"
  homepage "https://github.com/pablovilas/caw"
  version "0.0.1"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/pablovilas/caw/releases/download/v0.0.1/caw_0.0.1_darwin_arm64.tar.gz"
    sha256 "c3a27829dee94961d61be9ed977eb7a5a814814e6985a519a50692e3bcce8817"

    define_method(:install) do
      bin.install "caw"
    end
  end

  test do
    system "#{bin}/caw", "--help"
  end
end
